### ISSUE TITLE
Cyrillic text support

### ISSUE THREAD

**Issue by annapogorelova** [dijs/infobox-parser#12]
Hi @dijs and thank you very much for the great work!

I have tried parsing the wikitext of the article in Cyrillic language (Ukrainian) and looks like the lib doesn't support the Cyrillic text.

```
var infoboxParser = require("infobox-parser");
var result = infoboxParser(`{{Вулиця України
|назва = Вулиця Підвальна
|населений пункт = Львів
}}`)
```
Currently this code results in an empty object.

Do you plan to add a support for the Cyrillic text?

**Comment by dijs** [comment]
Ooo, I would love to. But I may need some help with that... 

Could you find a simple article we could test parsing with?

And maybe provide a english version as well?

**Comment by annapogorelova** [comment]
Sure. See the links below (a short article about Orion Nebula in English, Ukrainian and Russian):

[English](https://en.wikipedia.org/wiki/Orion_Nebula)
[Ukrainian](https://uk.wikipedia.org/wiki/%D0%A2%D1%83%D0%BC%D0%B0%D0%BD%D0%BD%D1%96%D1%81%D1%82%D1%8C_%D0%9E%D1%80%D1%96%D0%BE%D0%BD%D0%B0)
[Russian](https://ru.wikipedia.org/wiki/%D0%A2%D1%83%D0%BC%D0%B0%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D1%8C_%D0%9E%D1%80%D0%B8%D0%BE%D0%BD%D0%B0)

**Comment by dijs** [comment]
Interesting... So, I just added tests around this article. And it seems to work just fine. You can see here:

https://github.com/dijs/infobox-parser/pull/13

**Comment by annapogorelova** [comment]
Yes, you are right, it works. Maybe I missed something previously, sorry. Anyway, thank you!
