### ISSUE TITLE
incorrect field conversions

### ISSUE THREAD

**Issue by yonirabin** [dijs/infobox-parser#17]
for the infobox in wiki page - https://en.wikipedia.org/wiki/90_West_Street
"height" receives value 'convert' instead of the real value which is: "324.02 feet (98.76 m)"
"area"  receives value 'convert' instead of the real value which is: "0.39 acres (0.16 ha)"

**Comment by dijs** [comment]
Ah nice, a fancy built in function for wikipedia.

I will add support for this. Great find, thank you.

**Comment by dijs** [comment]
This has been published in `infobox-parser@3.3.0` and `wikijs@5.2.1`

**Comment by yonirabin** [comment]
Thanks!!!

> 	
> Yoni Rabin
> VP R&D
> +972-54-4550265
> RealOneX.com
> 


> On May 30, 2019, at 6:07 PM, Richard van der Dys <notifications@github.com> wrote:
> 
> Closed #17 via 9feeb4e.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
This message and any included attachments are from RealOneX Ltd. and are 
intended only for the addressee. The information contained in this message 
is confidential and may constitute inside or non-public information under 
international and/or local securities laws. Unauthorized forwarding, 
printing, copying, distribution, or use of such information is strictly 
prohibited and may be unlawful. If you are not the addressee, please 
promptly delete this message and notify the sender of the delivery error by 
e-mail.
