### ISSUE TITLE
Incorrect field conversions

### ISSUE THREAD

**Issue by yonirabin** [dijs/infobox-parser#19]
Hi, me again! thanks for the fixes last time, I tried the last version 5.5.0 and found the following issues:

Page: https://en.wikipedia.org/wiki/Empire_State_Building

2 types of errors: fields:

1.
startDate: 'start date and age',  // March 17, 1930; 89 years ago[2]
completionDate: 'start date and age',
opening: 'start date and age',

2.
floorCount: 'efn', //102 [7][8][9][c]

thanks!

**Comment by dijs** [comment]
Thanks for the findings and the *very* helpful information.

Fixed in `v3.3.1`
